DROP TABLE IF EXISTS approvals CASCADE;

DROP TABLE IF EXISTS maintenance CASCADE;

DROP TABLE IF EXISTS bookings CASCADE;

DROP TABLE IF EXISTS equipment CASCADE;

DROP TABLE IF EXISTS categories CASCADE;

DROP TABLE IF EXISTS employees CASCADE;